; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -aggressive-instcombine -S | FileCheck %s

define i16 @phi(i8 %x) {

LoopHeader:
  %zext = zext i8 %x to i32
  br label %Loop

Loop:
  %zext2 = phi i32 [%zext, %LoopHeader], [%shl, %Loop]
  %j = phi i32 [0, %LoopHeader], [%i, %Loop]
  %shl = shl i32 %zext2, 1
  %trunc = trunc i32 %shl to i16
  %i = add i32 %j, 1
  %cmp = icmp eq i32 %i, 10
  br i1 %cmp, label %LoopEnd, label %Loop

LoopEnd:
  ret i16 %trunc
}
